Total = [Predictions.Landscape_Diversity.Sensitivities.Countries.DistanceMean_1,...
Predictions.Landscape_Diversity.Sensitivities.Countries.DistanceMean_2,...
Predictions.Landscape_Diversity.Sensitivities.Countries.DistanceMean_3,...
Predictions.Landscape_Diversity.Sensitivities.Countries.GI_TotalMean_1,...
Predictions.Landscape_Diversity.Sensitivities.Countries.GI_TotalMean_2,...
Predictions.Landscape_Diversity.Sensitivities.Countries.GI_TotalMean_3,...
Predictions.Landscape_Diversity.Sensitivities.Countries.GI_RoadMean_1,...
Predictions.Landscape_Diversity.Sensitivities.Countries.GI_RoadMean_2,...
Predictions.Landscape_Diversity.Sensitivities.Countries.GI_RoadMean_3,...
Predictions.Landscape_Diversity.Sensitivities.Countries.GI_OtherLinearMean_1,...
Predictions.Landscape_Diversity.Sensitivities.Countries.GI_OtherLinearMean_2,...
Predictions.Landscape_Diversity.Sensitivities.Countries.GI_OtherLinearMean_3,...
Predictions.Landscape_Diversity.Sensitivities.Countries.GI_AreaMean_1,...
Predictions.Landscape_Diversity.Sensitivities.Countries.GI_AreaMean_2,...
Predictions.Landscape_Diversity.Sensitivities.Countries.GI_AreaMean_3];

Rank = zeros(15,3);
Rank(:,:) = 2;
for i = 1:15
   Rank(i,(find(tester(i,:) == max(tester(i,:))))) = 1;
   Rank(i,(find(tester(i,:) == min(tester(i,:))))) = 3;
end